# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 293)
        self.verticalLayoutWidget = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(30, 20, 361, 271))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.vlayout_main = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.vlayout_main.setContentsMargins(0, 0, 0, 0)
        self.vlayout_main.setObjectName("vlayout_main")
        self.table_widget_coffee = QtWidgets.QTableWidget(self.verticalLayoutWidget)
        self.table_widget_coffee.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.table_widget_coffee.setObjectName("table_widget_coffee")
        self.table_widget_coffee.setColumnCount(0)
        self.table_widget_coffee.setRowCount(0)
        self.vlayout_main.addWidget(self.table_widget_coffee)
        self.button_add = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.button_add.setObjectName("button_add")
        self.vlayout_main.addWidget(self.button_add)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Кофеёчик 2"))
        self.button_add.setText(_translate("Form", "Добавить"))
